development:
  # Register in sandbox veritrans and get your keys here:
  # https://dashboard.sandbox.midtrans.com/settings/config_info
  client_key: <%= Rails.application.credentials.midtrans[:client_key] %>
  server_key: <%= Rails.application.credentials.midtrans[:server_key] %>
  api_host: https://api.sandbox.midtrans.com

production:
  # Register and get your keys here:
  # https://dashboard.midtrans.com/settings/config_info
  # client_key: <%= ENV['VERITRANS_CLIENT_KEY'] %>
  # server_key: <%= ENV['VERITRANS_SERVER_KEY'] %>
  client_key: <%= Rails.application.credentials.midtrans[:production][:client_key] %>
  server_key: <%= Rails.application.credentials.midtrans[:production][:server_key] %>
  api_host: https://api.midtrans.com

staging:
  client_key: <%= ENV['VT_SANDBOX_CLIENT_KEY'] %>
  server_key: <%= ENV['VT_SANDBOX_SERVER_KEY'] %>
  api_host: https://api.sandbox.midtrans.com
